theme = "soho"
baseurl = "https://example.com/"
languageCode = "en"
title = "Abbey Dengler"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5

[params]
title = "Abbey Dengler"
description = "Masters in Applied Statistics"
# gravatar = "soho@example.com"
images = ["images/headshot.png"]
profilePicture = "images/headshot.png"
copyright = "Abbey Dengler"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["post"]

## Set custom theme color.
# themeColor = "#fc2803"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/abbey-dengler-639b451a1/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/abbeydengler"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
  name = "Experience"
  weight = 20
  identifier = "Experiences"
  url = "/Experience/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  identifier = "contact"
  weight = 40
  url = "/contact/"
  
    [[menu.main]]
  name = "Education"
  identifier = "Education"
  weight = 30
  url = "/education/"
  
  [[menu.main]]
  name = "Posts"
  weight = 50
  identifier = "posts"
  url = "/posts/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
